name: Deploy Frontend to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Google Cloud SDK
        run: |
          curl -sSL https://sdk.cloud.google.com | bash
          echo "source \$HOME/google-cloud-sdk/path.bash.inc" >> \$GITHUB_ENV
          gcloud version

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::8} #create a unique tag based on time and commit hash
          docker buildx build --push \
            --tag flamware/capiot:$IMAGE_TAG \
            .
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure GCP credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GKE_CREDENTIALS }}'

      - name: Set GKE context
        run: |
          gcloud container clusters get-credentials capiot-eu-cluster --region europe-west9 --project awesome-vigil-454917-q7

      - name: Update Kubernetes deployment
        run: |
          sed -i "s|image:.*|image: flamware/capiot:${{ steps.docker_build.outputs.image_tag }}|g" ./front-deployment.yaml
          kubectl apply -f ./front-deployment.yaml -n capiot-app
          kubectl rollout status deployment/frontend-deployment -n capiot-app --timeout=60s