name: Deploy Frontend to Google Cloud Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Google Cloud SDK and gke-gcloud-auth-plugin
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: gke-gcloud-auth-plugin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::8}
          docker build --push --no-cache \
            --build-arg VITE_API_URL=http://flamware.work/api \
            --build-arg VITE_INFLUXDB_URL=http://flamware.work/influxdb \
            --tag flamware/capiot:$IMAGE_TAG .
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_CREDENTIALS }}'

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: capiot-cluster
          location: europe-west1-b
          project_id: arcane-grin-458811-h4

      - name: Update Kubernetes deployment and YAML
        run: |
          kubectl set image deployment/frontend-deployment frontend-container=flamware/capiot:${{ steps.docker_build.outputs.image_tag }} -n capiot
          kubectl rollout status deployment/frontend-deployment -n capiot
          kubectl get deployment frontend-deployment -n capiot yaml > frontend-deployment.yaml